import type { Metadata } from "next";
import { NextFontWithVariable } from "next/dist/compiled/@next/font";
import { Manrope, Poppins } from "next/font/google";
import { cookies } from "next/headers";
import React from "react";
import { getLangDir } from "rtl-detect";
import MainLayout from "@/Library/Common/Layouts/MainLayout";

const poppins: NextFontWithVariable = Manrope({
	weight: ["500", "600", "700"],
	style: ["normal"],
	display: "swap",
	subsets: ["latin"],
	variable: "--poppins-font",
});

export const metadata: Metadata = {
	title: "Student Portal | ELPMP.com",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookiesJar = cookies();
	// @ts-ignore
	const locale = cookiesJar.get("NEXT_LOCALE")?.value ?? "en";
	// const nonce: string | null = headers().get("x-nonce");
	const direction: "ltr" | "rtl" = getLangDir(locale);

	return (
		<html className={poppins.variable} lang={locale} dir={direction}>
			<MainLayout>{children}</MainLayout>
		</html>
	);
}
